export const defaults = {
  hero: {
    badge: "Pet Sitter de confiança",
    title_part1: "O cuidado que o seu",
    title_highlight: "melhor amigo",
    title_part2: "merece",
    subtitle: "Passeios, pet sitting e hospedagem familiar com muito carinho, paciência e atenção. O João trata do seu pet como se fosse dele.",
    cta_primary: "Agendar Passeio/Estadia",
    cta_secondary: "Ver serviços",
    stat1: "+200 pets felizes",
    stat2: "5★ no Instagram",
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=900&q=80",
    badge_card_title: "Disponível esta semana",
    badge_card_subtitle: "Reserve já o seu horário",
  },
  about: {
    eyebrow: "Conheça o João",
    title: "Cuidar de pets é a minha paixão",
    paragraph1: "Sou o João, apaixonado por animais desde sempre.",
    paragraph2: "No meu Instagram @weneedgsus partilho diariamente as aventuras dos meus clientes peludos.",
    instagram_handle: "weneedgsus",
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&q=80",
    experience_badge: "🐾 +5 anos a cuidar",
    card1_title: "Experiência comprovada",
    card1_text: "Centenas de pets cuidados",
    card2_title: "100% dedicado",
    card2_text: "Atenção personalizada",
  },
  services: {
    eyebrow: "Serviços",
    title: "Soluções para cada peludo",
    subtitle: "Escolha o serviço perfeito para o seu melhor amigo.",
    items: [
      { icon: "Footprints", title: "Dog Walking", desc: "Passeios diários.", img: "" },
      { icon: "Home", title: "Pet Sitting", desc: "Cuido em casa.", img: "" },
      { icon: "Hotel", title: "Hospedagem Familiar", desc: "Ambiente familiar 24/7.", img: "" },
    ] as Array<{ icon: string; title: string; desc: string; img: string }>,
  },
  instagram: {
    eyebrow: "Instagram",
    title: "Acompanhe as Aventuras",
    description: "Veja o dia-a-dia dos nossos peludos no Instagram @weneedgsus",
    handle: "weneedgsus",
    cta: "Seguir @weneedgsus",
    previews: [] as string[],
  },
  contact: {
    eyebrow: "Contacto",
    title: "Vamos cuidar do seu pet?",
    subtitle: "Preencha o formulário e o João responde-lhe rapidamente.",
    email: "",
    phone: "",
    whatsapp: "",
    area: "",
  },
  footer: {
    name: "João de Deus · Pet Sitter",
    instagram_handle: "weneedgsus",
    instagram_url: "https://instagram.com/weneedgsus",
    copyright: "Feito com 🐾",
  },
};
